[project]
name = "manga-image-translator"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = "GPL-3.0-only"
dependencies = [
    "arabic-reshaper",
    "backports-cached-property",
    "colorama",
    "einops",
    "freetype-py",
    "httpx",
    "langcodes[data]",
    "manga-ocr",
    "networkx",
    "numpy",
    "omegaconf",
    "openai",
    "opencv-python",
    "psutil>=7.2.2",
    "py3langid",
    "pyclipper",
    "pydantic",
    "pydensecrf @ https://github.com/lucasb-eyer/pydensecrf/archive/refs/heads/master.zip",
    "pyhyphen",
    "pyside6",
    "python-bidi",
    "python-dotenv",
    "regex",
    "requests",
    "rich",
    "scikit-image",
    "shapely",
    "torch",
    "torchvision",
    "tqdm",
]

[dependency-groups]
dev = [
    "pylint",
    "pytest",
    "pytest-asyncio",
    "pytest-xdist",
]

[tool.isort]
profile = 'black'
multi_line_output = 3
line_length = 100
py_version = 312


[tool.pylint]
disable = """
C,R,W,
c-extension-no-member
"""
additional-builtins = "display"
output-format = "colorized"
generated-members = ["torch.*", "cv2.*"]

[tool.pytest.ini_options]
addopts = "-ra -v -p no:faulthandler"
minversion = "6.0"
testpaths = ["test"]
pythonpath = ["."]
